"""Optional LLM free-form answering through an OpenAI-compatible endpoint.

The LLM is used only for conversational / knowledge answers. Structured data
answers always come from the query engine so numbers are never generated by the
model. When the LLM is disabled or unreachable, callers fall back to the
heuristic assistant.
"""

from __future__ import annotations

import logging
import time

import httpx

from app.ai.assistant import AnswerResult
from app.config import get_settings

logger = logging.getLogger(__name__)

_LANG_NAMES = {
    "en": "English",
    "te": "Telugu",
    "hi": "Hindi",
    "ta": "Tamil",
    "kn": "Kannada",
    "ml": "Malayalam",
    "bn": "Bengali",
    "gu": "Gujarati",
    "pa": "Punjabi",
    "or": "Odia",
    "as": "Assamese",
    "mr": "Marathi",
}

_SYSTEM_PROMPT = (
    "You are IN-GRES AI, a groundwater-resource assistant for India. Your first "
    "job is to UNDERSTAND the question — identify the real intent (level, "
    "availability, recharge, extraction, quality, rainfall, history, future "
    "prediction, trend, comparison, cause, risk, recommendation, calculation), "
    "the location and the time period — BEFORE answering.\n\n"
    "ANSWER-SHAPE RULES (match the question word):\n"
    "- WHAT is / HOW MUCH / HOW MANY → give the value FIRST, with unit, location, "
    "period and source; then brief supporting context.\n"
    "- WHY / cause questions → 1) direct reason, 2) supporting evidence "
    "(extraction vs recharge, rainfall trend), 3) local factors, 4) consequence. "
    "Never reply with bare statistics when a cause was asked for.\n"
    "- WHETHER ('is it declining?') → start with 'Yes.' / 'No.' / 'Uncertain.', "
    "then the evidence.\n"
    "- WHEN → date/period/timeline. WHERE → places/areas affected.\n"
    "- HOW → explain the process or give actionable steps.\n"
    "- COMPARISON of two places → a small markdown table with one row per "
    "indicator, then say which is better/worse and why.\n"
    "- PREDICTION → current situation → historical trend → predicted value/range "
    "→ uncertainty/confidence → key factors. Never present a forecast as "
    "guaranteed fact; label it a statistical estimate.\n\n"
    "QUALITY RULES:\n"
    "- ALWAYS answer the exact question asked — never a different one, never a "
    "generic definition when specifics were asked.\n"
    "- Lead with the direct answer in 1–3 sentences. No throat-clearing like "
    "'Groundwater is an important component…'.\n"
    "- Every number needs value + unit + location + period + source context.\n"
    "- Use only relevant information; skip unrelated data even if available.\n"
    "- Plain, natural language a normal user understands; simple words unless "
    "technical detail was requested.\n"
    "- Reply in the SAME language as the user's latest message, using their "
    "script (English, Telugu, Hindi, any other).\n"
    "- Read the conversation: resolve 'it', 'there', 'this area', 'next year' "
    "against earlier turns before answering.\n"
    "- If the question is ambiguous and references cannot be resolved from "
    "context, ask ONE short clarifying question instead of guessing.\n\n"
    "DATA RULES:\n"
    "1. Never invent specific official statistics (exact stage-of-extraction %, "
    "recharge volumes) for Indian states/districts as if they came from IN-GRES/"
    "CGWB. For those, say the app's data services provide them and suggest asking "
    "e.g. 'recharge in Telangana'. General explanations and well-known approximate "
    "facts are fine.\n"
    "2. If knowledge-base context is provided, prefer basing your answer on it.\n"
    "3. If WEB RESULTS are provided, base your answer on them, stay faithful to "
    "what they say (they are live internet findings), and end with a short line "
    "\"Sources: <domain1>, <domain2>\" listing the sites you actually used.\n"
    "4. If you genuinely don't know something and no context helps, say so "
    "briefly rather than guessing."
)


def _request_chat(
    backend: dict[str, str],
    messages: list[dict],
    temperature: float,
    max_tokens: int,
    timeout: int | None = None,
    tools: list[dict] | None = None,
    tool_choice: str | dict | None = None,
) -> dict | None:
    """One chat-completions call against a specific backend.

    Transient failures (413 from agentic search payloads, 429 rate limits,
    5xx) are retried a couple of times with a short backoff. Permanent
    failures (401 invalid key, 400 model_decommissioned / model_not_found)
    return None immediately so callers can fall back.
    """
    settings = get_settings()
    payload: dict = {
        "model": backend["model"],
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if tools:
        payload["tools"] = tools
    if tool_choice is not None:
        payload["tool_choice"] = tool_choice
    if "11434" in backend["base_url"]:
        payload["keep_alive"] = "30m"
    headers = (
        {"Authorization": f"Bearer {backend['api_key']}"}
        if backend.get("api_key")
        else {}
    )
    attempts = 3 if backend["provider"] != "ollama" else 1
    for attempt in range(attempts):
        try:
            with httpx.Client(timeout=timeout or settings.LLM_TIMEOUT_SECONDS) as client:
                resp = client.post(
                    f"{backend['base_url']}/chat/completions",
                    json=payload,
                    headers=headers,
                )
                if resp.status_code in (413, 429) or resp.status_code >= 500:
                    raise httpx.HTTPStatusError(
                        f"transient {resp.status_code}", request=resp.request, response=resp
                    )
                if resp.status_code in (400, 401, 403, 404):
                    # Permanent: bad key, unknown/decommissioned model, bad
                    # tool payload. Log the server message once and stop —
                    # callers fall back to DuckDuckGo / next backend.
                    try:
                        detail = resp.json()
                    except Exception:  # noqa: BLE001
                        detail = resp.text[:300]
                    logger.warning(
                        "LLM %s/%s permanent %s: %s",
                        backend["provider"], backend["model"],
                        resp.status_code, detail,
                    )
                    return None
                resp.raise_for_status()
                return resp.json()
        except httpx.HTTPStatusError as exc:
            if attempt < attempts - 1:
                retry_after = exc.response.headers.get("retry-after")
                wait = float(retry_after) if retry_after else 1.0 * (attempt + 1)
                logger.warning(
                    "LLM %s/%s transient %s, retrying in %.1fs",
                    backend["provider"], backend["model"], exc.response.status_code, wait,
                )
                time.sleep(min(wait, 8))
                continue
            logger.warning("LLM %s/%s failed: %s", backend["provider"], backend["model"], exc)
            return None
        except Exception as exc:  # noqa: BLE001 - caller decides how to fall back
            logger.warning("LLM call to %s/%s failed: %s", backend["provider"], backend["model"], exc)
            return None
    return None


def _post_messages(
    messages: list[dict], temperature: float, max_tokens: int, timeout: int | None = None
) -> dict | None:
    """Try each configured backend in order; return the first success."""
    settings = get_settings()
    chain = settings.llm_backend_chain()
    for i, backend in enumerate(chain):
        # A cloud provider without a key can never work — skip straight to the
        # next backend (local Ollama) instead of burning an auth round-trip.
        if not backend.get("api_key") and backend["provider"] != "ollama":
            logger.info("LLM backend %s skipped (no API key)", backend["provider"])
            continue
        data = _request_chat(backend, messages, temperature, max_tokens, timeout)
        if data is not None:
            return data
        last = " (no further backends)" if i == len(chain) - 1 else ", trying next backend"
        logger.warning("LLM backend %s failed%s", backend["provider"], last)
    return None


_MAX_HISTORY_TURNS = 6
_MAX_HISTORY_CHARS = 1200


def _history_messages(history: list[dict] | None) -> list[dict]:
    """Recent turns as chat messages so follow-up questions keep context."""
    msgs: list[dict] = []
    for item in (history or [])[-_MAX_HISTORY_TURNS:]:
        content = str(item.get("content") or "").strip()
        role = item.get("role")
        if not content or role not in ("user", "assistant"):
            continue
        if len(content) > _MAX_HISTORY_CHARS:
            content = content[:_MAX_HISTORY_CHARS] + "…"
        msgs.append({"role": role, "content": content})
    return msgs


def generate(
    text: str,
    language: str,
    chunks: list[str] | None = None,
    history: list[dict] | None = None,
    web_results: list[dict] | None = None,
) -> AnswerResult | None:
    """Generate a free-form answer. Returns None if unavailable.

    ``history`` carries recent conversation turns ({"role", "content"}) so the
    model can resolve follow-up questions against what was already asked.
    ``web_results`` are live internet search hits ({"title", "url", "snippet"})
    used when the knowledge base has nothing relevant; sources are cited.
    """
    if not get_settings().LLM_ENABLED:
        return None

    lang = language if language in _LANG_NAMES else "en"
    user_parts: list[str] = [f"User question: {text}"]
    if chunks:
        context = "\n\n".join(f"- {c}" for c in chunks[:3])
        user_parts.append(f"Relevant knowledge context (verbatim):\n{context}")
    if web_results:
        web_block = "\n\n".join(
            f"[{i + 1}] {r.get('title', '')} — {r.get('url', '')}\n{r.get('snippet', '')}"
            for i, r in enumerate(web_results[:5])
        )
        user_parts.append(f"WEB RESULTS (live internet search):\n{web_block}")
    data = _post_messages(
        [
            {"role": "system", "content": _SYSTEM_PROMPT},
            *_history_messages(history),
            {"role": "user", "content": "\n\n".join(user_parts)},
        ],
        temperature=0.3,
        max_tokens=600,
    )
    if not data:
        return None
    try:
        content = data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError):
        return None
    if not content:
        return None

    if web_results:
        sources = ["Web search"] + [
            r.get("url", "") for r in web_results[:5] if r.get("url")
        ]
    else:
        sources = ["IN-GRES AI knowledge base"]

    return AnswerResult(
        content=content,
        response_type="conversational",
        intent="fallback",
        language=lang,
        sources=sources,
        is_demo=False,
    )


_SEARCH_SYSTEM_PROMPT = (
    "You are IN-GRES AI's live web-research agent for the Indian Groundwater "
    "Resource Estimation System. You have built-in internet search — USE IT "
    "before answering, then reply in the SAME language as the user (their "
    "script), directly and concisely (under about 200 words, plain text).\n\n"
    "RULES:\n"
    "1. Never invent specific official statistics (exact stage-of-extraction %, "
    "recharge volumes) for Indian states/districts as if they came from IN-GRES/"
    "CGWB.\n"
    "2. Stay faithful to what the search results say; do not blend in guesses.\n"
    "3. End with a short line \"Sources: <domain1>, <domain2>\" listing the sites "
    "you actually used."
)


def _extract_search_urls(data: dict) -> list[str]:
    """Pull the URLs the search tool actually visited out of the response.

    Handles both the legacy Compound ``executed_tools`` shape and the
    gpt-oss ``browser_search`` tool-call shape (tool results / citations may
    appear under ``tool_calls``, ``citations``, or nested ``results``).
    """
    urls: list[str] = []

    def walk(node: object) -> None:
        if isinstance(node, dict):
            url = node.get("url")
            if isinstance(url, str) and url.startswith("http"):
                urls.append(url)
            # Groq browser_search citations sometimes use href/link/source.
            for key in ("href", "link", "source"):
                val = node.get(key)
                if isinstance(val, str) and val.startswith("http"):
                    urls.append(val)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    message = {}
    try:
        message = data["choices"][0]["message"]
    except (KeyError, IndexError, TypeError):
        return []
    # Legacy Compound field + gpt-oss tool-call/citation fields.
    for field in ("executed_tools", "tool_calls", "citations", "browser_results"):
        tools = message.get(field) or []
        walk(tools)
    # Also walk tool-role messages (Exa results are sometimes returned there).
    try:
        for choice_msg in data.get("choices", []):
            for extra in ("tool_messages", "messages"):
                walk(choice_msg.get(extra) or [])
    except Exception:  # noqa: BLE001 - URL extraction is best-effort
        pass
    seen: set[str] = set()
    ordered = []
    for u in urls:
        if u not in seen:
            seen.add(u)
            ordered.append(u)
    return ordered


# Groq models with server-side browser search (Exa-powered). Must be called
# with tools=[{"type": "browser_search"}]. See
# https://console.groq.com/docs/tool-use/built-in-tools/browser-search
_GROQ_BROWSER_SEARCH_MODELS = frozenset(
    {
        "openai/gpt-oss-120b",
        "openai/gpt-oss-20b",
        "openai/gpt-oss-safeguard-20b",
    }
)


def _supports_groq_browser_search(backend: dict[str, str]) -> bool:
    return (
        backend.get("provider") == "groq"
        and (backend.get("model") or "").strip() in _GROQ_BROWSER_SEARCH_MODELS
    )


def generate_search(
    text: str,
    language: str,
    history: list[dict] | None = None,
) -> AnswerResult | None:
    """Answer by letting the model search the internet itself.

    Primary path: Groq ``openai/gpt-oss-120b`` (or -20b) with the built-in
    ``browser_search`` tool — the supported replacement for the
    decommissioned ``groq/compound`` system (EOL 2026-09-21).

    Explicit fallback (preserves Compound-like behaviour when the native
    tool is unavailable): DuckDuckGo search + the normal answer model via
    :func:`generate`. Returns None only when neither path can answer, so
    callers keep their existing ``llm_generate_search or ddgs`` flow.
    """
    settings = get_settings()
    if not settings.LLM_ENABLED:
        return None
    backend = settings.llm_search_backend()
    if backend is None or not backend.get("api_key"):
        return None

    lang = language if language in _LANG_NAMES else "en"
    messages = [
        {"role": "system", "content": _SEARCH_SYSTEM_PROMPT},
        *_history_messages(history),
        {"role": "user", "content": f"User question: {text}"},
    ]

    data = None
    if _supports_groq_browser_search(backend):
        # Native server-side browsing: the model decides when to search.
        # tool_choice="required" forces a search pass for web-fallback
        # questions (mirrors Compound's always-search behaviour).
        data = _request_chat(
            backend,
            messages,
            temperature=0.3,
            max_tokens=800,
            tools=[{"type": "browser_search"}],
            tool_choice="required",
        )
        if data is not None:
            try:
                content = data["choices"][0]["message"]["content"].strip()
            except (KeyError, IndexError, TypeError, AttributeError):
                content = ""
            if content:
                urls = _extract_search_urls(data)
                sources = ["Web search", *urls[:5]] if urls else ["Web search"]
                return AnswerResult(
                    content=content,
                    response_type="conversational",
                    intent="fallback",
                    language=lang,
                    sources=sources,
                    is_demo=False,
                )
            logger.info("Groq browser_search returned no content; using ddgs fallback")
    else:
        # Non-Groq provider or a custom LLM_SEARCH_MODEL without a native
        # search tool: try a plain call first (model knowledge), then ddgs.
        data = _request_chat(
            backend,
            messages,
            temperature=0.3,
            max_tokens=800,
        )
        if data is not None:
            try:
                content = data["choices"][0]["message"]["content"].strip()
            except (KeyError, IndexError, TypeError, AttributeError):
                content = ""
            if content:
                urls = _extract_search_urls(data)
                sources = ["Web search", *urls[:5]] if urls else ["Web search"]
                return AnswerResult(
                    content=content,
                    response_type="conversational",
                    intent="fallback",
                    language=lang,
                    sources=sources,
                    is_demo=False,
                )

    # Explicit tool orchestration fallback (replaces Compound automation):
    # User -> ddgs search -> model (with results as context) -> cited answer.
    # This is the same path the orchestrator would take next, but doing it
    # here keeps a single "search answer" entry point with sources attached.
    if not settings.WEB_SEARCH_ENABLED:
        return None
    try:
        from app.rag.websearch import search as ddgs_search

        web_results = ddgs_search(text)
    except Exception as exc:  # noqa: BLE001 - search is best-effort
        logger.warning("ddgs fallback search failed: %s", exc)
        return None
    if not web_results:
        return None
    return generate(
        text, lang, chunks=None, history=history, web_results=web_results
    )


_FACT_COMPOSER_RULES = (
    "\n\nCOMPOSITION MODE — VERIFIED FACTS PROVIDED:\n"
    "You are given authoritative facts computed from the IN-GRES dataset for "
    "this exact question. Compose the final user reply from them.\n"
    "- Keep EVERY number, unit, location, year and category EXACTLY as given. "
    "Never round, recompute, drop or invent figures.\n"
    "- You may reorganise, clarify and add well-known non-statistical context.\n"
    "- Follow the answer-shape rules (direct answer first, match the question "
    "word) and reply in the user's language/script."
)


def compose_answer(
    text: str,
    language: str,
    facts: str,
    history: list[dict] | None = None,
) -> str | None:
    """Let the LLM write the final reply from verified dataset facts.

    Returns the composed text, or None when unavailable (caller keeps the
    template answer). Numbers stay grounded because ``facts`` is authoritative.
    """
    if not get_settings().LLM_ENABLED:
        return None
    lang = language if language in _LANG_NAMES else "en"
    data = _post_messages(
        [
            {"role": "system", "content": _SYSTEM_PROMPT + _FACT_COMPOSER_RULES},
            *_history_messages(history),
            {
                "role": "user",
                "content": (
                    f"User question: {text}\n\n"
                    f"VERIFIED DATASET FACTS (authoritative — use these numbers):\n"
                    f"{facts}"
                ),
            },
        ],
        temperature=0.3,
        max_tokens=600,
    )
    if not data:
        return None
    try:
        content = data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError):
        return None
    return content or None


_TRANSLATE_PROMPT = (
    "You are a precise translator for IN-GRES AI, a groundwater information "
    "assistant for India.\n\n"
    "Translate the assistant's reply into the SAME language the user is writing in "
    "using its native script (the user's original message is given in <user_message>).\n\n"
    "RULES:\n"
    "1. Translate all prose into the user's language.\n"
    "2. Keep every number, percentage, year, unit (hm³, %, mm, bcm) and measurement "
    "EXACTLY as in the original. Never change, round, recompute or reformat figures.\n"
    "3. Keep line breaks, bullet points and bold ** markers.\n"
    "4. Keep proper nouns and agency names (CGWB, IMD, state/district/village names) in the "
    "original or transliterated form.\n"
    "5. Output ONLY the translation, with no preamble or explanation."
)


def translate(text: str, language: str, source_text: str | None = None) -> str | None:
    """Translate an assistant reply into the user's language.

    Returns the translated text, or None when the LLM is disabled or unreachable
    (callers fall back to the original English text). Translation preserves all
    figures verbatim so data answers keep their exact numbers.
    """
    if not get_settings().LLM_ENABLED:
        return None

    lang = language if language in _LANG_NAMES else language
    user_parts = [
        f"<user_message>\n{source_text or ''}\n</user_message>",
        f"<assistant_reply>\n{text}\n</assistant_reply>",
        f"Target language: {lang}",
    ]
    data = _post_messages(
        [
            {"role": "system", "content": _TRANSLATE_PROMPT},
            {"role": "user", "content": "\n\n".join(user_parts)},
        ],
        temperature=0.0,
        max_tokens=1200,
        timeout=min(get_settings().LLM_TIMEOUT_SECONDS, 30),
    )
    if not data:
        return None
    try:
        content = data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError):
        return None
    return content or None