"""initial schema

Revision ID: 16ce5699bb0a
Revises: 
Create Date: 2026-08-13 20:56:54.867403

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


revision = '16ce5699bb0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('language_pref', sa.String(length=10), nullable=False),
    sa.Column('phone_number_masked', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('geographic_level', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('document_version', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number_masked', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_call_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_user_id'), 'voice_calls', ['user_id'], unique=False)
    op.create_table('assessment_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_units_centroid', 'assessment_units', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index('idx_assessment_units_geom', 'assessment_units', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_assessment_units_district_id'), 'assessment_units', ['district_id'], unique=False)
    op.create_index(op.f('ix_assessment_units_name'), 'assessment_units', ['name'], unique=False)
    op.create_index(op.f('ix_assessment_units_state_id'), 'assessment_units', ['state_id'], unique=False)
    op.create_table('expert_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_expert_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_expert_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_requests_assigned_expert_id'), 'expert_requests', ['assigned_expert_id'], unique=False)
    op.create_index(op.f('ix_expert_requests_conversation_id'), 'expert_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_expert_requests_status'), 'expert_requests', ['status'], unique=False)
    op.create_index(op.f('ix_expert_requests_user_id'), 'expert_requests', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('mandals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandals_district_id'), 'mandals', ['district_id'], unique=False)
    op.create_index(op.f('ix_mandals_name'), 'mandals', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('response_type', sa.String(length=30), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('voice_transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_call_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('stt_provider', sa.String(length=50), nullable=True),
    sa.Column('stt_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['voice_call_id'], ['voice_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_transcriptions_voice_call_id'), 'voice_transcriptions', ['voice_call_id'], unique=False)
    op.create_table('groundwater_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_unit_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('recharge_total', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('extraction_total', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('annual_extractable_resource', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('stage_of_extraction', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_unit_id'], ['assessment_units.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_assessments_assessment_unit_id'), 'groundwater_assessments', ['assessment_unit_id'], unique=False)
    op.create_index(op.f('ix_groundwater_assessments_assessment_year'), 'groundwater_assessments', ['assessment_year'], unique=False)
    op.create_index(op.f('ix_groundwater_assessments_category'), 'groundwater_assessments', ['category'], unique=False)
    op.create_index(op.f('ix_groundwater_assessments_dataset_id'), 'groundwater_assessments', ['dataset_id'], unique=False)
    op.create_table('groundwater_extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_unit_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('extraction_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_unit_id'], ['assessment_units.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_extraction_assessment_unit_id'), 'groundwater_extraction', ['assessment_unit_id'], unique=False)
    op.create_index(op.f('ix_groundwater_extraction_dataset_id'), 'groundwater_extraction', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_groundwater_extraction_year'), 'groundwater_extraction', ['year'], unique=False)
    op.create_table('groundwater_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_unit_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('measured_date', sa.Date(), nullable=True),
    sa.Column('depth_bgl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_level_class', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_unit_id'], ['assessment_units.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_levels_assessment_unit_id'), 'groundwater_levels', ['assessment_unit_id'], unique=False)
    op.create_index(op.f('ix_groundwater_levels_dataset_id'), 'groundwater_levels', ['dataset_id'], unique=False)
    op.create_table('groundwater_recharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_unit_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('recharge_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_unit_id'], ['assessment_units.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groundwater_recharge_assessment_unit_id'), 'groundwater_recharge', ['assessment_unit_id'], unique=False)
    op.create_index(op.f('ix_groundwater_recharge_dataset_id'), 'groundwater_recharge', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_groundwater_recharge_year'), 'groundwater_recharge', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groundwater_recharge_year'), table_name='groundwater_recharge')
    op.drop_index(op.f('ix_groundwater_recharge_dataset_id'), table_name='groundwater_recharge')
    op.drop_index(op.f('ix_groundwater_recharge_assessment_unit_id'), table_name='groundwater_recharge')
    op.drop_table('groundwater_recharge')
    op.drop_index(op.f('ix_groundwater_levels_dataset_id'), table_name='groundwater_levels')
    op.drop_index(op.f('ix_groundwater_levels_assessment_unit_id'), table_name='groundwater_levels')
    op.drop_table('groundwater_levels')
    op.drop_index(op.f('ix_groundwater_extraction_year'), table_name='groundwater_extraction')
    op.drop_index(op.f('ix_groundwater_extraction_dataset_id'), table_name='groundwater_extraction')
    op.drop_index(op.f('ix_groundwater_extraction_assessment_unit_id'), table_name='groundwater_extraction')
    op.drop_table('groundwater_extraction')
    op.drop_index(op.f('ix_groundwater_assessments_dataset_id'), table_name='groundwater_assessments')
    op.drop_index(op.f('ix_groundwater_assessments_category'), table_name='groundwater_assessments')
    op.drop_index(op.f('ix_groundwater_assessments_assessment_year'), table_name='groundwater_assessments')
    op.drop_index(op.f('ix_groundwater_assessments_assessment_unit_id'), table_name='groundwater_assessments')
    op.drop_table('groundwater_assessments')
    op.drop_index(op.f('ix_voice_transcriptions_voice_call_id'), table_name='voice_transcriptions')
    op.drop_table('voice_transcriptions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_mandals_name'), table_name='mandals')
    op.drop_index(op.f('ix_mandals_district_id'), table_name='mandals')
    op.drop_table('mandals')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_expert_requests_user_id'), table_name='expert_requests')
    op.drop_index(op.f('ix_expert_requests_status'), table_name='expert_requests')
    op.drop_index(op.f('ix_expert_requests_conversation_id'), table_name='expert_requests')
    op.drop_index(op.f('ix_expert_requests_assigned_expert_id'), table_name='expert_requests')
    op.drop_table('expert_requests')
    op.drop_index(op.f('ix_assessment_units_state_id'), table_name='assessment_units')
    op.drop_index(op.f('ix_assessment_units_name'), table_name='assessment_units')
    op.drop_index(op.f('ix_assessment_units_district_id'), table_name='assessment_units')
    op.drop_index('idx_assessment_units_geom', table_name='assessment_units', postgresql_using='gist')
    op.drop_index('idx_assessment_units_centroid', table_name='assessment_units', postgresql_using='gist')
    op.drop_table('assessment_units')
    op.drop_index(op.f('ix_voice_calls_user_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_table('states')
    op.drop_table('assessment_categories')
    # ### end Alembic commands ###